version: "3.9"

services:
  kdatabase:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432

volumes:
  db-data: