//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "exerciseable_external")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub link: String,
    pub exerciseable_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::exerciseable::Entity",
        from = "Column::ExerciseableId",
        to = "super::exerciseable::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Exerciseable,
}

impl Related<super::exerciseable::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Exerciseable.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
