//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use super::sea_orm_active_enums::ExerciseableType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "exercise")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub idea_id: Uuid,
    pub exerciseable_id: Uuid,
    pub exerciseable_type: Option<ExerciseableType>,
    pub title: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::exerciseable_notecard::Entity",
        from = "Column::ExerciseableId",
        to = "super::exerciseable_notecard::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ExerciseableNotecard,
    #[sea_orm(
        belongs_to = "super::idea::Entity",
        from = "Column::IdeaId",
        to = "super::idea::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Idea,
}

impl Related<super::exerciseable_notecard::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExerciseableNotecard.def()
    }
}

impl Related<super::idea::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Idea.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
