//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use super::sea_orm_active_enums::ExplainableType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "explanation")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub explainable_type: Option<ExplainableType>,
    pub idea_id: Uuid,
    pub explainable_id: Uuid,
    pub title: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::explainable::Entity",
        from = "Column::ExplainableId",
        to = "super::explainable::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Explainable,
    #[sea_orm(
        belongs_to = "super::idea::Entity",
        from = "Column::IdeaId",
        to = "super::idea::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Idea,
}

impl Related<super::explainable::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Explainable.def()
    }
}

impl Related<super::idea::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Idea.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
