//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "explainable_markdown")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub explainable_id: Uuid,
    pub markdown: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::explainable::Entity",
        from = "Column::ExplainableId",
        to = "super::explainable::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Explainable,
}

impl Related<super::explainable::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Explainable.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
