//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "explainable")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::explainable_external::Entity")]
    ExplainableExternal,
    #[sea_orm(has_many = "super::explainable_markdown::Entity")]
    ExplainableMarkdown,
    #[sea_orm(has_many = "super::explanation::Entity")]
    Explanation,
}

impl Related<super::explainable_external::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExplainableExternal.def()
    }
}

impl Related<super::explainable_markdown::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExplainableMarkdown.def()
    }
}

impl Related<super::explanation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Explanation.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
