//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

pub use super::card::Entity as Card;
pub use super::exercise::Entity as Exercise;
pub use super::exerciseable::Entity as Exerciseable;
pub use super::exerciseable_external::Entity as ExerciseableExternal;
pub use super::exerciseable_notecard::Entity as ExerciseableNotecard;
pub use super::explainable::Entity as Explainable;
pub use super::explainable_external::Entity as ExplainableExternal;
pub use super::explainable_markdown::Entity as ExplainableMarkdown;
pub use super::explanation::Entity as Explanation;
pub use super::idea::Entity as Idea;
pub use super::usr::Entity as Usr;
