//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "exerciseable_type")]
pub enum ExerciseableType {
    #[sea_orm(string_value = "External")]
    External,
    #[sea_orm(string_value = "Notecard")]
    Notecard,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "explainable_type")]
pub enum ExplainableType {
    #[sea_orm(string_value = "External")]
    External,
    #[sea_orm(string_value = "Markdown")]
    Markdown,
}
